function b(n,e){if(e){const t=e.match(/arxiv\.org\/(?:abs|pdf)\/([^/]+)/);return t?`arxiv:${t[1].replace(/v\d+$/,"")}`:`url:${e}`}return`title:${n.toLowerCase().replace(/\s+/g,"-")}`}function w(n){var v,h,m;const e=n.querySelector(".gs_rt a"),t=(e==null?void 0:e.textContent)||"",r=((v=n.querySelector(".gs_a"))==null?void 0:v.textContent)||"",[a,s]=r.split(" - "),o=s==null?void 0:s.match(/\b(\d{4})\b/),l=o?parseInt(o[1],10):new Date().getFullYear(),c=((h=n.querySelector(".gs_rs"))==null?void 0:h.textContent)||"",d=(e==null?void 0:e.getAttribute("href"))||void 0,p=Array.from(n.querySelectorAll(".gs_fl a")).find(M=>{var f;return(f=M.textContent)==null?void 0:f.includes("Cited by")}),S=p?parseInt(((m=p.textContent)==null?void 0:m.replace("Cited by","").trim())||"0",10):0,g=n.querySelector(".gs_or_ggsm a"),C=(g==null?void 0:g.getAttribute("href"))||void 0;return{id:b(t,d),title:t,authors:a.trim(),year:l,abstract:c,sourceURL:d,pdfURL:C,citations:S}}let i=null,u=null;const x='<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.456 2.456L21.75 6l-1.035.259a3.375 3.375 0 00-2.456 2.456zM16.898 20.572L16.5 21.75l-.398-1.178a3.375 3.375 0 00-2.456-2.456L12.5 17.25l1.178-.398a3.375 3.375 0 002.456-2.456L16.5 13.5l.398 1.178a3.375 3.375 0 002.456 2.456l1.178.398-1.178.398a3.375 3.375 0 00-2.456 2.456z" /></svg>';function y(){var n;document.getElementById("are-copilot-panel")||(i=document.createElement("div"),i.id="are-copilot-panel",i.className="are-copilot-panel",i.innerHTML=`
        <div class="are-copilot-header">
            <h2 id="are-copilot-title">AI Co-Pilot</h2>
            <button class="are-copilot-close-btn" title="Close"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" /></svg></button>
        </div>
        <div class="are-copilot-content" id="are-copilot-content"><div class="are-loading">Select a paper to analyze.</div></div>
    `,document.body.appendChild(i),(n=i.querySelector(".are-copilot-close-btn"))==null||n.addEventListener("click",()=>i==null?void 0:i.classList.remove("visible")))}function q(n){u=n,i||y(),i==null||i.classList.add("visible");const e=i.querySelector("#are-copilot-content");e.innerHTML='<div class="are-loading">Analyzing with AI...</div>',chrome.runtime.sendMessage({action:"getAiAnalysisForPaper",paper:u},t=>{t!=null&&t.success?k(t.data.summary,t.data.analysis):e.innerHTML="<p>Error fetching analysis.</p>"})}function k(n,e){var s,o;const t=i.querySelector("#are-copilot-content"),r=e.keyFindings.map(l=>`<li>${l}</li>`).join(""),a=e.limitations.map(l=>`<li>${l}</li>`).join("");t.innerHTML=`
        <div class="are-copilot-section"><h3>Summary</h3><p>${n}</p></div>
        <div class="are-copilot-section"><h3>Analysis</h3><p><strong>Research Question:</strong> ${e.researchQuestion}</p><p><strong>Methodology:</strong> ${e.methodology}</p></div>
        <div class="are-copilot-section"><h3>Key Findings</h3><ul>${r}</ul></div>
        <div class="are-copilot-section"><h3>Limitations</h3><ul>${a}</ul></div>
        <div class="are-copilot-section" id="are-tools-section">
            <h3>Tools</h3>
            <div id="are-pdf-tool"><button class="are-copilot-tool-button" id="are-find-pdf-btn">Find Open Access PDF</button></div>
            <div id="are-suggestions-tool" style="margin-top: 10px;"><button class="are-copilot-tool-button" id="are-get-suggestions-btn">Generate Search Ideas</button></div>
        </div>
    `,(s=document.getElementById("are-find-pdf-btn"))==null||s.addEventListener("click",P),(o=document.getElementById("are-get-suggestions-btn"))==null||o.addEventListener("click",$)}function P(n){const e=n.target;e.disabled=!0,e.textContent="Searching...",chrome.runtime.sendMessage({action:"findOpenAccessForPaper",paper:u},t=>{const r=document.getElementById("are-pdf-tool");t!=null&&t.success&&t.pdfUrl?r.innerHTML=`<a href="${t.pdfUrl}" target="_blank" rel="noopener noreferrer" class="are-copilot-tool-button">Open PDF</a>`:r.innerHTML='<p style="font-size: 0.875rem; text-align: center;">No open access PDF found.</p>'})}function $(n){const e=n.target;e.disabled=!0,e.textContent="Generating...",chrome.runtime.sendMessage({action:"getSuggestionsForPaper",paper:u},t=>{const r=document.getElementById("are-suggestions-tool");if(t!=null&&t.success&&t.suggestions.length>0){const a=t.suggestions.map(s=>`<li><button data-query="${s}">${s}</button></li>`).join("");r.innerHTML=`<ul class="are-copilot-suggestion-list">${a}</ul>`,r.querySelectorAll("button").forEach(s=>{s.addEventListener("click",()=>{const o=s.dataset.query;window.open(`https://scholar.google.com/scholar?q=${encodeURIComponent(o)}`,"_blank")})})}else r.innerHTML='<p style="font-size: 0.875rem; text-align: center;">Could not generate suggestions.</p>'})}function L(){y(),document.querySelectorAll(".gs_r.gs_or.gs_scl").forEach(e=>{const t=e,r=t.querySelector(".gs_fl");if(!r||t.querySelector(".are-save-button"))return;const a=w(t);if(!a.title)return;const s=b(a.title,a.sourceURL),o=document.createElement("button");o.className="are-save-button",o.innerHTML='<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" d="M17.593 3.322c1.1.128 1.907 1.077 1.907 2.185V21L12 17.5 4.5 21V5.507c0-1.108.806-2.057 1.907-2.185a48.507 48.507 0 0111.186 0z" /></svg><span>Save</span>',chrome.runtime.sendMessage({action:"getPaperStatus",paperId:s},c=>{c!=null&&c.exists&&(o.classList.add("are-saved"),o.querySelector("span").textContent="Saved",o.disabled=!0)}),o.addEventListener("click",c=>{c.preventDefault(),c.stopPropagation(),o.disabled=!0,o.querySelector("span").textContent="Saving...",chrome.runtime.sendMessage({action:"savePaper",paper:a},d=>{d!=null&&d.success?(o.classList.add("are-saved"),o.querySelector("span").textContent="Saved"):(o.querySelector("span").textContent="Error",setTimeout(()=>{o.disabled=!1,o.querySelector("span").textContent="Save"},2e3))})}),r.appendChild(o);const l=document.createElement("button");l.className="are-copilot-trigger",l.innerHTML=`${x} <span>AI Co-Pilot</span>`,l.addEventListener("click",c=>{c.preventDefault(),c.stopPropagation(),q(a)}),r.appendChild(l)})}const I=new MutationObserver(()=>{document.querySelector(".gs_r.gs_or.gs_scl:not(:has(.are-save-button))")&&L()});I.observe(document.body,{childList:!0,subtree:!0});L();
