
import React, { useState, useEffect } from 'react';
import { Download, Loader2, FileText, CheckCircle2, AlertCircle, TrendingUp, ShieldCheck, Cpu } from 'lucide-react';
import * as apiService from '../services/apiService';
import { ProjectReport as ProjectReportType } from '../types';

interface ProjectReportProps {
    metrics: {
        datasetSize: number;
        testAccuracy: number;
        studySessions: number;
        totalEvents: number;
    };
}

export const ProjectReport: React.FC<ProjectReportProps> = ({ metrics }) => {
    const [report, setReport] = useState<ProjectReportType | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        generateReport();
    }, []);

    const generateReport = async () => {
        setIsLoading(true);
        setError(null);
        try {
            const data = await apiService.generateProjectReport(metrics);
            setReport(data);
        } catch (e) {
            setError("Failed to generate project report. Please try again later.");
            console.error(e);
        } finally {
            setIsLoading(false);
        }
    };

    const handleDownload = () => {
        if (!report) return;

        const content = `
${report.title}
==================================================

SUMMARY:
${report.summary}

PERFORMANCE METRICS:
${report.performanceMetrics.map(m => `- ${m.label}: ${m.value} (${m.description})`).join('\n')}

FUTURE-PROOFING STRATEGY:
${report.futureProofing.map(fp => `
--- ${fp.category} ---
${fp.recommendations.map(r => `- ${r}`).join('\n')}
`).join('\n')}

TECHNICAL ALTERNATIVES:
${report.technicalAlternatives.map(alt => `
--- ${alt.name} ---
Description: ${alt.description}
Pros: ${alt.pros.join(', ')}
Cons: ${alt.cons.join(', ')}
`).join('\n')}

SOURCE PAPERS (ARXIV):
${report.sourcePapers.map(p => `- ${p.title} (${p.year})`).join('\n')}

Generated by Scholar Explorer Project Engine - ${new Date().toLocaleString()}
        `;

        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `Scholar_Explorer_Project_Report.txt`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    if (isLoading) {
        return (
            <div className="h-96 flex flex-col items-center justify-center space-y-4 bg-white rounded-3xl border border-slate-100 shadow-sm">
                <Loader2 className="w-12 h-12 text-slate-900 animate-spin" />
                <div className="text-center">
                    <p className="text-xl font-extrabold tracking-tight text-slate-900">Generating Project Report...</p>
                    <p className="text-slate-500 text-sm">Analyzing metrics and synthesizing future-proofing strategy</p>
                </div>
            </div>
        );
    }

    if (error) {
        return (
            <div className="p-12 bg-red-50 rounded-[2rem] border border-red-100 flex flex-col items-center text-center space-y-4">
                <AlertCircle className="w-12 h-12 text-red-500" />
                <div>
                    <h3 className="text-xl font-bold text-red-900">Report Generation Failed</h3>
                    <p className="text-red-700 max-w-md mx-auto mt-2">{error}</p>
                    <button 
                        onClick={generateReport}
                        className="mt-6 px-8 py-3 bg-red-600 text-white rounded-2xl hover:bg-red-700 transition-all font-bold shadow-lg shadow-red-600/20"
                    >
                        Try Again
                    </button>
                </div>
            </div>
        );
    }

    if (!report) return null;

    return (
        <div className="space-y-12 animate-in fade-in slide-in-from-bottom-4 duration-500">
            {/* Header with Download */}
            <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                <div>
                    <h2 className="text-4xl font-extrabold tracking-tight text-slate-900">{report.title}</h2>
                    <p className="text-slate-500 mt-2">Comprehensive analysis of project standing and long-term resilience.</p>
                </div>
                <button 
                    onClick={handleDownload}
                    className="px-8 py-4 bg-slate-900 text-white rounded-2xl font-bold flex items-center gap-2 hover:bg-slate-800 transition-all shadow-xl shadow-slate-900/20 active:scale-95 whitespace-nowrap"
                >
                    <Download className="w-5 h-5" />
                    Export Report (.txt)
                </button>
            </div>

            {/* Summary */}
            <div className="p-8 rounded-[2rem] bg-indigo-50 border border-indigo-100">
                <p className="text-indigo-900 text-lg leading-relaxed font-medium italic">
                    {report.summary}
                </p>
            </div>

            {/* Metrics Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                {report.performanceMetrics.map((m, i) => (
                    <div key={i} className="p-8 rounded-[2rem] bg-white border border-slate-100 shadow-sm hover:shadow-md transition-all">
                        <TrendingUp className="w-8 h-8 text-indigo-600 mb-4" />
                        <div className="text-3xl font-black text-slate-900 mb-1">{m.value}</div>
                        <div className="text-xs font-black uppercase tracking-widest text-slate-400 mb-4">{m.label}</div>
                        <p className="text-slate-500 text-sm leading-relaxed">{m.description}</p>
                    </div>
                ))}
            </div>

            {/* Future Proofing */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                <div className="space-y-6">
                    <div className="flex items-center gap-3">
                        <ShieldCheck className="w-6 h-6 text-emerald-600" />
                        <h3 className="text-2xl font-extrabold tracking-tight text-slate-900">Future-Proofing Strategy</h3>
                    </div>
                    <div className="space-y-4">
                        {report.futureProofing.map((fp, i) => (
                            <div key={i} className="p-6 rounded-3xl bg-slate-50 border border-slate-100">
                                <h4 className="text-sm font-black uppercase tracking-widest text-slate-400 mb-4">{fp.category}</h4>
                                <ul className="space-y-3">
                                    {fp.recommendations.map((r, ri) => (
                                        <li key={ri} className="flex items-start gap-3 text-slate-600 text-sm">
                                            <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 flex-shrink-0" />
                                            {r}
                                        </li>
                                    ))}
                                </ul>
                            </div>
                        ))}
                    </div>
                </div>

                <div className="space-y-6">
                    <div className="flex items-center gap-3">
                        <Cpu className="w-6 h-6 text-indigo-600" />
                        <h3 className="text-2xl font-extrabold tracking-tight text-slate-900">Technical Alternatives</h3>
                    </div>
                    <div className="space-y-4">
                        {report.technicalAlternatives.map((alt, i) => (
                            <div key={i} className="p-6 rounded-3xl bg-white border border-slate-100 shadow-sm">
                                <h4 className="text-lg font-bold text-slate-900 mb-2">{alt.name}</h4>
                                <p className="text-slate-500 text-xs mb-4">{alt.description}</p>
                                <div className="flex flex-wrap gap-2">
                                    {alt.pros.slice(0, 2).map((pro, pi) => (
                                        <span key={pi} className="px-2 py-0.5 rounded-md bg-emerald-50 text-emerald-700 text-[10px] font-bold uppercase tracking-wider">
                                            {pro}
                                        </span>
                                    ))}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* Sources */}
            <div className="p-8 rounded-[2rem] bg-slate-50 border border-slate-100">
                <h4 className="text-xs font-black uppercase tracking-widest text-slate-400 mb-6">Research Sources (ArXiv)</h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {report.sourcePapers.map((p, i) => (
                        <div key={i} className="flex items-center gap-3 p-4 bg-white rounded-2xl border border-slate-100">
                            <FileText className="w-5 h-5 text-slate-300" />
                            <div className="min-w-0">
                                <div className="text-sm font-bold text-slate-900 truncate">{p.title}</div>
                                <div className="text-[10px] text-slate-400 font-mono">{p.year}</div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
};
